# Generated by Django 5.0.2 on 2024-02-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('released_at', models.DateField()),
                ('oracle_id', models.CharField(max_length=100)),
                ('tcgplayer_id', models.IntegerField()),
                ('cardmarket_id', models.IntegerField()),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_image', models.URLField()),
                ('normal_image', models.URLField()),
                ('png_image', models.URLField()),
                ('art_crop_image', models.URLField()),
                ('border_crop_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana_cost', models.CharField(max_length=100)),
                ('type_line', models.CharField(max_length=100)),
                ('oracle_text', models.TextField()),
                ('power', models.CharField(max_length=100)),
                ('toughness', models.CharField(max_length=100)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cardapp.card')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField(null=True)),
                ('usd_foil', models.FloatField(null=True)),
                ('usd_etched', models.FloatField(null=True)),
                ('eur', models.FloatField(null=True)),
                ('eur_foil', models.FloatField(null=True)),
                ('tix', models.FloatField(null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cardapp.card')),
            ],
        ),
        migrations.CreateModel(
            name='Ruiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateField()),
                ('comment', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruilings', to='cardapp.card')),
            ],
        ),
    ]
