# Generated by Django 5.0.2 on 2024-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0002_remove_card_oracle_id_alter_card_id_rulings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='power',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='toughness',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='large_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='art_crop_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='border_crop_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='normal_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='png_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='small_image',
            field=models.URLField(null=True),
        ),
    ]
