# Generated by Django 5.0.2 on 2024-03-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0003_remove_attributes_power_remove_attributes_toughness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='oracle_text',
        ),
    ]
