# Generated by Django 5.0.2 on 2024-03-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0004_remove_attributes_oracle_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
