# Generated by Django 5.0.2 on 2024-03-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0005_delete_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_uris', to='cardapp.card'),
            preserve_default=False,
        ),
    ]
