# Generated by Django 5.0.2 on 2024-03-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0006_cardimage_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='card',
        ),
    ]
