# Generated by Django 5.0.2 on 2024-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0008_remove_prices_card_remove_rulings_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rulings',
            name='card',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
