# Generated by Django 5.0.2 on 2024-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0009_cardimage_card_prices_card_rulings_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardmarket_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='released_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rulings',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rulings',
            name='published_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rulings',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
