# Generated by Django 5.0.2 on 2024-03-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0010_alter_card_cardmarket_id_alter_card_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cardapp.card'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cardapp.card'),
        ),
        migrations.AlterField(
            model_name='rulings',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='cardapp.card'),
        ),
    ]
