# Generated by Django 5.0.2 on 2024-03-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0011_alter_cardimage_card_alter_prices_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulings',
            name='card',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
