# Generated by Django 5.0.2 on 2024-03-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0013_remove_cardimage_card_remove_prices_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cardapp.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cardapp.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulings',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cardapp.card'),
            preserve_default=False,
        ),
    ]
