# Generated by Django 5.0.2 on 2024-03-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0014_cardimage_card_prices_card_rulings_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardmarket_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tcgplayer_id',
        ),
    ]
