# Generated by Django 5.0.2 on 2024-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0015_remove_card_cardmarket_id_remove_card_tcgplayer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rulings',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
